
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-test-team
  namespace: default
subjects:
# - kind: Group
#   name: oidc:mcp-k8s:test-team
#   apiGroup: rbac.authorization.k8s.io
- kind: User
  name: oidc:admin@example.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-test-team
  namespace: kube-system
subjects:
# - kind: Group
#   name: oidc:mcp-k8s:test-team
#   apiGroup: rbac.authorization.k8s.io
- kind: User
  name: oidc:admin@example.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
