apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test-deployment
  labels:
    app: nginx
spec:
# for the purpose of testing how we work with the deployment
# we only need to have the deployment itself, not the pods,
# so we set replicas to 0
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
