# This is Github workflow that installs mcp-k8s from npm to various platforms and tests if it was installed

name: Install mcp-k8s

on:
  schedule:
    # check that the install works periodically 
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        os: 
          - windows-latest
          - ubuntu-latest
          - macos-latest
        arch: 
          - x64
          - arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install mcp-k8s from docker
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          docker pull mcpk8s/server:latest
          docker run --rm mcpk8s/server:latest version

      - name: Install mcp-k8s from npm
        run: |
          npm install -g @strowk/mcp-k8s
          mcp-k8s version
